name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install

      - name: Run Robot Framework
        run: poetry run robot components/tests/tests.robot
        
      - name: Run tests
        run: poetry run coverage run --branch -m pytest
      - name: Create coverage report
        run: poetry run coverage xml
      - name: Send coverage report to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Run Pylint
        run: poetry run pylint src
